# SQLite version 3.x
#   gem install postgresql
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'postgresql'
#

development:
  adapter: postgresql
  encoding: unicode
  database: my_test_app_development
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: my_test_app_test
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  
production:
  adapter: postgresql
  encoding: unicode
  database: my_test_app_production
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: postgres
  password: postgres